### PR TITLE
Ruby 3 compatibility

### LINKED ISSUE #262: Broken CI: template is not valid
The CI is broken after the last commits.

1. [[CI] Server - Unit tests](https://github.com/decidim/decidim-bulletin-board/runs/5705120399?check_suite_focus=true) 

> Error: .github/workflows/server-workflow.yml (Line: 161, Col: 16):
> Error: The template is not valid. .github/workflows/server-workflow.yml (Line: 161, Col: 16): hashFiles('voting_schemes/electionguard/python-wrapper/**') failed. Fail to hash files under directory '/home/runner/work/decidim-bulletin-board/decidim-bulletin-board'
> 

2. In [[CI] Server - E2E tests](https://github.com/decidim/decidim-bulletin-board/runs/5705120379?check_suite_focus=true)

> (...)
> Bundle complete! 6 Gemfile dependencies, 61 gems now installed.
> Use `bundle info [gemname]` to see where a bundled gem is installed.
> cd voting_schemes/electionguard/python-wrapper && make install
> make[1]: Entering directory '/__w/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper'
> python3 -m pip install --upgrade pip
> Requirement already satisfied: pip in /root/.pyenv/versions/3.8.11/lib/python3.8/site-packages (21.1.1)
> Collecting pip
>   Downloading pip-22.0.4-py3-none-any.whl (2.1 MB)
> Installing collected packages: pip
>   Attempting uninstall: pip
>     Found existing installation: pip 21.1.1
>     Uninstalling pip-21.1.1:
>       Successfully uninstalled pip-21.1.1
> WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv
> Successfully installed pip-22.0.4
> cd ../electionguard-python && make environment build
> make[2]: Entering directory '/__w/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/electionguard-python'
> 🔧 ENVIRONMENT SETUP
> make install-gmp
> make[3]: Entering directory '/__w/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/electionguard-python'
> 📦 Install gmp
> Operating System identified as Linux
> make install-gmp-linux
> make[4]: Entering directory '/__w/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/electionguard-python'
> 🐧 LINUX INSTALL
> sudo apt-get install libgmp-dev
> Reading package lists...
> Building dependency tree...
> Reading state information...
> The following additional packages will be installed:
>   libgmp10 libgmpxx4ldbl
> Suggested packages:
>   gmp-doc libgmp10-doc
> The following packages will be upgraded:
>   libgmp-dev libgmp10 libgmpxx4ldbl
> 3 upgraded, 0 newly installed, 0 to remove and 74 not upgraded.
> Need to get 903 kB of archives.
> After this operation, 1024 B of additional disk space will be used.
> Do you want to continue? [Y/n] Abort.
> make[4]: *** [Makefile:55: install-gmp-linux] Error 1
> make[4]: Leaving directory '/__w/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/electionguard-python'
> make[3]: *** [Makefile:34: install-gmp] Error 2
> make[3]: Leaving directory '/__w/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/electionguard-python'
> make[2]: *** [Makefile:13: environment] Error 2
> make[2]: Leaving directory '/__w/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/electionguard-python'
> make[1]: *** [Makefile:9: install] Error 2
> make[1]: Leaving directory '/__w/decidim-bulletin-board/decidim-bulletin-board/voting_schemes/electionguard/python-wrapper'
> make: *** [voting_schemes/electionguard/makefile.mk:93: install_electionguard_python_wrapper] Error 2
> Error: Process completed with exit code 2.
> (...)

### PR DESCRIPTION
**Pull request by ahukkanen**
This PR started with updating the Graphlient gem but it turned out to a wider Ruby 3 upgrade where we upgrade also other gems as well as the base docker image. After this is completed, we can publish a new version of the gem which allows us to update Decidim to Ruby 3.

The current version of the Graphlient gem is not Ruby 3 compatible but 0.5.0 makes it run on Ruby 3.

This is an issue for upgrading Decidim to Ruby 3 as discussed at https://github.com/decidim/decidim/pull/8452.

Fixes #262.

### CODE REVIEW

**Comment by ahukkanen** [comment]
We need to release a new version of the base Docker image (ruby-node-python-electionguard) which is currently under the Codegram organization at DockerHub:
https://hub.docker.com/u/codegram

It is based on this Dockerfile:
https://github.com/decidim/decidim-bulletin-board/blob/5b79ff859f3754bd4270e986094b7a26414e132c/voting_schemes/electionguard/docker/ruby-node-python-electionguard/Dockerfile

So this is what I want to discuss about @andreslucena, we need to release this under the Decidim organization and then update the Docker image references accordingly.

File: bulletin_board/server/app/models/election.rb [hunk 1]
```diff
@@ -8,7 +8,7 @@ class Election < ApplicationRecord
 
   has_one_attached :verifiable_results
 
-  enum status: { created: 0, key_ceremony: 1, key_ceremony_ended: 2, vote: 3, vote_ended: 4, tally: 5, tally_ended: 6, results_published: 7 }
+  enum status: { created: 0, key_ceremony: 1, key_ceremony_ended: 2, vote: 3, vote_ended: 4, tally_started: 5, tally_ended: 6, results_published: 7 }
```
Comment (ahukkanen) [inline bulletin_board/server/app/models/election.rb:11]: Just FYI, this change needed to be done because Ruby 2.7 added `Enumerable#tally` which conflicts with this name:
https://ruby-doc.org/core-3.0.2/Enumerable.html#method-i-tally

There is an error printed in the console saying that the Active Record relation already has a method named `tally` which is why it cannot be used as an enumeration key.

File: bulletin_board/server/db/migrate/20200826103217_change_client_fields.rb [hunk 2]
```diff
@@ -1,6 +1,6 @@
 # frozen_string_literal: true
 
-class ChangeClientFields < ActiveRecord::Migration[6.0]
+class ChangeClientFields < ActiveRecord::Migration[6.1]
```
Comment (ahukkanen) [inline bulletin_board/server/db/migrate/20200826103217_change_client_fields.rb:3]: I needed to change the migration defaults to Rails 6.1 to avoid schema changes.

If we keep it as 6.0, the primary keys in the `db/schema.rb` would be changed from `:bigint` to `:integer`.

File: bulletin_board/server/app/controllers/sandbox/elections_controller.rb [hunk 3]
```diff
@@ -38,7 +40,7 @@ def vote
 
       pending_message = bulletin_board_client.cast_vote(election_id, params[:voter_id], params[:encrypted_ballot])
 
-      render json: pending_message.to_json
+      render json: { data: pending_message.to_h }
```
Comment (ahukkanen) [inline bulletin_board/server/app/controllers/sandbox/elections_controller.rb:43]: Stack level too deep when using `#to_json`.

File: bulletin_board/server/app/controllers/sandbox/elections_controller.rb [hunk 4]
```diff
@@ -84,7 +86,7 @@ def tally; end
     def report_missing_trustee
       pending_message = bulletin_board_client.report_missing_trustee(election_id, params[:trustee_id])
 
-      render json: pending_message.to_json
+      render json: { data: pending_message.to_h }
```
Comment (ahukkanen) [inline bulletin_board/server/app/controllers/sandbox/elections_controller.rb:89]: Stack level too deep when using `#to_json`.

**Review by ahukkanen — COMMENTED** [review]
These I needed to change because the `pending_message.to_json` was causing a "Stack level too deep" error after the gems update.

**Comment by ahukkanen** [comment]
@andreslucena All tests are now passing, so I would appreciate if you could take a look as well. I left some review comments to help you out above.

Most of the changes are in the configurations (i.e. Ruby 3.0.2 instead of Ruby 2.6.6) and some minor changes in the server application. For the ruby-client itself the only other change is upgrading `graphlient` to the `0.5.x` version which supports Ruby 3.

File: bulletin_board/server/app/controllers/sandbox/elections_controller.rb [hunk 5]
```diff
@@ -254,9 +256,5 @@ def bulk_votes_file_update_time(election)
     def generated_votes_number(election)
       `wc -l "#{bulk_votes_file_path(election)}"`.strip.split(" ")[0].to_i
     end
-
-    def redis
-      Redis.current
```
Comment (ahukkanen) [inline bulletin_board/server/app/controllers/sandbox/elections_controller.rb:259]: `Redis.current` is deprecated which is why this is removed.

File: bulletin_board/server/app/jobs/sandbox/generate_votes_job.rb [hunk 6]
```diff
@@ -69,9 +71,5 @@ def client
     def log_entry_for(message_type)
       election.log_entries.where(message_type: message_type).last
     end
-
-    def redis
-      Redis.current
```
Comment (ahukkanen) [inline bulletin_board/server/app/jobs/sandbox/generate_votes_job.rb:74]: `Redis.current` is deprecated which is why this is removed.

File: bulletin_board/server/app/services/concerns/redis_provider.rb [hunk 7]
```diff
@@ -0,0 +1,16 @@
+# frozen_string_literal: true
+
+module RedisProvider
```
Comment (ahukkanen) [inline bulletin_board/server/app/services/concerns/redis_provider.rb:3]: This is added due to the deprecation of `Redis.current`.

File: bulletin_board/server/config/initializers/redis.rb [hunk 8]
```diff
@@ -1,7 +0,0 @@
-# frozen_string_literal: true
```
Comment (ahukkanen) [inline bulletin_board/server/config/initializers/redis.rb:1]: `Redis.current=` is deprecated which is why this is removed.

**Review by ahukkanen — COMMENTED** [review]
The `Redis.current` and `Redis.current=` methods are deprecated which is why these changes have been done:
https://github.com/redis/redis-rb/blob/5fb64bdecacac0bc5738f194ab82cd1001071879/lib/redis.rb#L40
https://github.com/redis/redis-rb/blob/5fb64bdecacac0bc5738f194ab82cd1001071879/lib/redis.rb#L45

**Comment by andreslucena** [comment]
Code wise I see it all OK. I didn't have the chance to try this out locally.  

As we've talked Wednesday, I'm in the process of trying this app integration with Decidim, but I'm actually blocked in one specific step of the process (already reported at #9120). 

What we can try meanwhile, so we don't block this merge, is the Sandbox feature, just to be sure that everything works as expected. It emulates all the different steps of an Election. I don't know if you've already checked that, but if not, I can try to do that Monday and let you know.

**Comment by ahukkanen** [comment]
> What we can try meanwhile, so we don't block this merge, is the Sandbox feature, just to be sure that everything works as expected. It emulates all the different steps of an Election. I don't know if you've already checked that, but if not, I can try to do that Monday and let you know.

@andreslucena Yes I've played with the sandbox and to me everything seems to work correctly.

There is also the Cypress E2E integration tests in this repo which I believe should run through all the functionality the Sandbox app provides, right? These tests are also part of the CI and passing.

https://github.com/decidim/decidim-bulletin-board/blob/22dfe760e25bf07db85eaf421e4c39b5e2a6eec1/bulletin_board/server/cypress/integration/sandbox/election.spec.js#L3

**Comment by andreslucena** [comment]
Oh great, if sandbox is covered by specs, and you've checked that manually, then we're good to go for me!

**Review by andreslucena — APPROVED** [review]
👍🏽

**Comment by ahukkanen** [comment]
Yes, I've tested all the actions in the sandbox app and to me they all seem to work. I could not get the tally process to work automatically without "Restoring" the keys, if I understood correctly it should read it automatically from the browser's database without having to "restore" the key from the backup file. But this may be just a problem with my browser (or the client implementation) and I don't think anything in the app has changed with this part (as it's front-end functionality).

Only thing I noticed is that sometimes when I click e.g. "Start tally", the state won't update in the view but after I refresh the page, it is updated. This is because some actions in the sandbox app won't wait for the action to finish at the bulletin board before sending the response to the client, e.g. in this case:
https://github.com/decidim/decidim-bulletin-board/blob/22dfe760e25bf07db85eaf421e4c39b5e2a6eec1/bulletin_board/server/app/controllers/sandbox/elections_controller.rb#L78-L79

But I believe this is a problem also in the current version of the sandbox app, nothing is changed with these actions with the Ruby 3 update and the E2E tests still work (it's just a matter how fast you are loading the view after the redirect).

**Comment by ahukkanen** [comment]
@andreslucena I did a small change still after testing this with the Decidim integration.

We will also need to release a new version of the bulletin board docker image, so I changed that also to reference the Decidim organization at DockerHub. I will push the image there once this PR is merged.
